### ISSUE TITLE
HTTP status code 401 trying to login with version 2.1.0

### ISSUE THREAD

**Issue by tbraas** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#209]
I'm setting up a fresh instance of HB to finally tie all my loose IoT ends up.

It would appear that the API published by Panasonic has changed in some way as I am getting a 401 for my requests. I am not sure how to fix the problem. Please see below:

[2/23/2024, 12:56:32 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 7792) is running on port 51682.
[2/23/2024, 12:56:33 AM] [Homebridge Panasonic AC Platform] The latest App Store version is 1.20.0.
[2/23/2024, 12:56:33 AM] [Homebridge Panasonic AC Platform] Attempting to log into Comfort Cloud.
[2/23/2024, 12:56:33 AM] [Homebridge Panasonic AC Platform] Comfort Cloud: login()
[2/23/2024, 12:56:33 AM] [Homebridge Panasonic AC Platform] UTC date: 2024-02-22 13:56:33
[2/23/2024, 12:56:33 AM] [Homebridge Panasonic AC Platform] Local date: 2024-02-23 00:56:33
[2/23/2024, 12:56:33 AM] [Homebridge Panasonic AC Platform] 2FA code: 935260 (for key NFGCGMKG...PVZSIZRT)
[2/23/2024, 12:56:34 AM] [Homebridge Panasonic AC Platform] Comfort Cloud - login(): Error
[2/23/2024, 12:56:34 AM] [Homebridge Panasonic AC Platform] {
  "message": "Request failed with status code 401",
  "name": "AxiosError",
  "stack": "AxiosError: Request failed with status code 401\n    at settle (/homebridge/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/adapters/http.js:589:11)\n    at IncomingMessage.emit (node:events:529:35)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/homebridge/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/core/Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json; charset=UTF-8",
      "Content-Type": "application/json",
      "User-Agent": "G-RAC",
      "X-APP-NAME": "Comfort Cloud",
      "X-APP-TIMESTAMP": "20240222 13:56:33",
      "X-APP-TYPE": "0",
      "X-APP-VERSION": "1.20.0",
      "X-CFC-API-KEY": "0",
      "Content-Length": "82",
      "Accept-Encoding": "gzip, compress, deflate, br"
    },
    "method": "post",
    "url": "https://accsmart.panasonic.com/auth/login",
    "data": "{\"loginId\":\"**********************\",\"language\":0,\"password\":\"**************\"}"
  },
  "code": "ERR_BAD_REQUEST",
  "status": 401
}
[2/23/2024, 12:56:34 AM] [Homebridge Panasonic AC Platform] Successfully logged in to Comfort Cloud.
[2/23/2024, 12:56:34 AM] [Homebridge Panasonic AC Platform] Discovering devices on Comfort Cloud.
[2/23/2024, 12:56:34 AM] [Homebridge Panasonic AC Platform] Comfort Cloud: getDevices()
[2/23/2024, 12:56:34 AM] [Homebridge Panasonic AC Platform] An error occurred during device discovery. Turn on debug mode for more information.
[2/23/2024, 12:56:34 AM] [Homebridge Panasonic AC Platform] No auth token available (login probably failed). Check your credentials and restart Homebridge.

**Comment by mkz212** [comment]
@tbraas 

- Can you log in to the Panasonic Comfort Cloud app? And can you control the devices there?
- Have you set 2FA using the app? Have you chosen SMS or TOTP (32 char code)?

**Comment by mkz212** [comment]
@tbraas Usually when there is a message that you logged in correctly and later an error message, the reason is an air conditioning communication error with Comfort Cloud. Turn off the air conditioning from the power completely and then turn it on. If that doesn't help, restart your routers and Homebridge.

**Comment by tbraas** [comment]
> @tbraas
> 
> * Can you log in to the Panasonic Comfort Cloud app? And can you control the devices there?
> * Have you set 2FA using the app? Have you chosen SMS or TOTP (32 char code)?

Yes, I can log in on my mobile and I'm using the 32 character code. 

The error code coming back suggests the request is malformed, something is missing or there's an unknown property in the request.

**Comment by mkz212** [comment]
@tbraas It works for me all the time. So far, every time there were such errors, it turned out to be a communication problem between AC and the Comfort Cloud server. But since you say that the application works for you and you can log in there and control each device...

**Comment by jandersonhill** [comment]
@tbraas I haven't seen any additional comments on this issue, I'm going to assume all is now ok and will close. If you are still having problems, please reopen this request.
