### ISSUE TITLE
Impossible to connect V2

### ISSUE THREAD

**Issue by M0rT4L13** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#326]
Hello, since this evening, the app no longer connects to Homebridge and the plugin. Everything was working perfectly until now, but now, nothing works.

I have tried everything:

Resetting 2FA
Resetting the password
Resetting the account

I don’t understand anything anymore.

What should I do?
![IMG_7347](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/assets/121009175/52a2eca9-dcc4-406f-9d86-bc05c8344236)

**Comment by mkz212** [comment]
@M0rT4L13 

I just tested it and it works for me without a problem, so this is not a global problem.

Check in the plugin readme in the troubleshoting section what you can do.

**Comment by phill-hunt** [comment]
Hi 8 have just had a similar problemas of today

**Comment by mkz212** [comment]
@phill-hunt Comfort Cloud service has a planned technical break.

**Comment by phill-hunt** [comment]
My ISO app is still working though

**Comment by mkz212** [comment]
@phill-hunt They announced technical work for today. I don't know what they doing there. My application also works and in Homebridge it is error. Let's wait, maybe it will resolve itself. Unless Panasonic has changed something in API again.

**Comment by phill-hunt** [comment]
Sounds good thanks

**Comment by hubert3** [comment]
Login also broken for me with plugin version 3.0.1, Panasonic Comfort Cloud v1.20.1 still works

```
[18/06/2024, 00:33:27] [Panasonic AC Platform] Comfort Cloud - login(): Error
[18/06/2024, 00:33:27] [Panasonic AC Platform] {
  "message": "Request failed with status code 403",
  "name": "AxiosError",
  "stack": "AxiosError: Request failed with status code 403\n    at settle (/usr/lib/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/adapters/http.js:589:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/usr/lib/node_modules/homebridge-panasonic-ac-platform/node_modules/axios/lib/core/Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http",
      "fetch"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Accept": "application/json; charset=UTF-8",
      "Content-Type": "application/json",
      "User-Agent": "G-RAC",
      "X-APP-NAME": "Comfort Cloud",
      "X-APP-TIMESTAMP": "20240617 14:33:27",
      "X-APP-TYPE": "0",
      "X-APP-VERSION": "1.20.1",
      "X-CFC-API-KEY": "0",
      "Content-Length": "80",
      "Accept-Encoding": "gzip, compress, deflate, br"
    },
    "method": "post",
    "url": "https://accsmart.panasonic.com/auth/login",
    "data": "{\"loginId\":\"xxx@xxx.com\",\"language\":0,\"password\":\"xxxx\"}"
  },
  "code": "ERR_BAD_REQUEST",
  "status": 403
}
[18/06/2024, 00:33:27] [Panasonic AC Platform] Error: Request failed with status code 403
[18/06/2024, 00:33:27] [Panasonic AC Platform] The Comfort Cloud server might be experiencing issues at the moment. If issue persists, make sure: configured is the correct email and password in plugin settings, field "Emulated Comfort Cloud app version (override)" in settings is empty or have the latest version of Panasonic Comfort Cloud from the App Store (like 1.19.0), the latest version of this plugin is installed, all terms and conditions after logging into Panasonic Comfort Cloud appare accepted and you can successfully login and control devices via app.Restart Homebridge if you change plugin settings.
[18/06/2024, 00:33:27] [Panasonic AC Platform] Next login attempt in 5 minutes.
```

**Comment by mkz212** [comment]
#330

**Comment by hubert3** [comment]
@M0rT4L13 your error from a week ago looks like it could be a DNS issue on your Homebridge system, can you ping accsmart.panasonic.com successfully from terminal?

Separately from that, there is a known issue due to the API having changed again as of today and the plugin doesn't work for anybody right now

**Comment by M0rT4L13** [comment]
I resolved the problem .

i deleted my 2 devices from Confort Cloud and reinstalled them, that’s all.

**Comment by mkz212** [comment]
New version solves this problem. Unfortunately, Panasonic has changed the API and no version is currently working. We are working on it: #330
