### ISSUE TITLE
5.0.0 - An error occurred during device discovery

### ISSUE THREAD

**Issue by panda-ng** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#493]
### Description

Starting version 5.0.0, there is error of [Panasonic AC Platform] An error occurred during device discovery. Turn on debug mode for more information.

Happen to buy a new AC, unable to add a new device properly with 5.0.0, need to roll back to 4.4.5 to add the device. After the new device is added successfully with 4.4.5, upgrading back to 5.0.0 will see the new device but the error still happens.

### Logs

```code
[9/6/2024, 10:06:51 AM] [Panasonic AC Platform] An error occurred during device discovery. Turn on debug mode for more information.
[9/6/2024, 10:06:51 AM] [Panasonic AC Platform] Error: Cannot add a Service with the same UUID 'xxxx' and subtype 'exposeInsideTemp' as another Service in this Accessory.
    at Accessory.addService (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:561:17)
    at PlatformAccessory.addService (/var/lib/homebridge/node_modules/homebridge/src/platformAccessory.ts:99:41)
    at new IndoorUnitAccessory (/var/lib/homebridge/node_modules/homebridge-panasonic-ac-platform/src/indoor-unit.ts:143:27)
    at PanasonicPlatform.discoverDevices (/var/lib/homebridge/node_modules/homebridge-panasonic-ac-platform/src/platform.ts:287:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Plugin version

5.0.0

**Comment by mkz212** [comment]
@panda-ng This may be due to the fact that the name requirements change in homebridge 2.0.0. You must remove devices from the cache (Homebridge settings).

**Comment by panda-ng** [comment]
@mkz212 , I see, indeed it is, and resolved now.

**Comment by panda-ng** [comment]
resolved
