### ISSUE TITLE
issue exist after update version to 5.2.1, before works fine

### ISSUE THREAD

**Issue by patrickyuen1** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#523]
### Description

04/11/2024, 21:21:42Panasonic Ac Platform BridgeWARNINGNo plugins installed.
04/11/2024, 21:21:42Panasonic Ac Platform BridgeLoading 1 platforms...
04/11/2024, 21:21:42Panasonic Ac Platform BridgeBridge is running on port 51826.
04/11/2024, 21:21:44Panasonic Ac Platform BridgeConfiguration change
04/11/2024, 21:21:44panasonicacplatformbridge stopping
04/11/2024, 21:21:49Panasonic Ac Platform Bridge starting
04/11/2024, 21:22:01Panasonic Ac Platform BridgeERRORError loading plugin "homebridge-panasonic-ac-platform"
04/11/2024, 21:22:01Panasonic Ac Platform BridgeERRORReadableStream is not defined
04/11/2024, 21:22:01Panasonic Ac Platform BridgeERRORReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/index.js:106:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)

### Logs

```code
04/11/2024, 21:21:42Panasonic Ac Platform BridgeWARNINGNo plugins installed.
04/11/2024, 21:21:42Panasonic Ac Platform BridgeLoading 1 platforms...
04/11/2024, 21:21:42Panasonic Ac Platform BridgeBridge is running on port 51826.
04/11/2024, 21:21:44Panasonic Ac Platform BridgeConfiguration change
04/11/2024, 21:21:44panasonicacplatformbridge stopping
04/11/2024, 21:21:49Panasonic Ac Platform Bridge starting
04/11/2024, 21:22:01Panasonic Ac Platform BridgeERRORError loading plugin "homebridge-panasonic-ac-platform"
04/11/2024, 21:22:01Panasonic Ac Platform BridgeERRORReadableStream is not defined
04/11/2024, 21:22:01Panasonic Ac Platform BridgeERRORReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/panasonicacplatformbridge/node_modules/undici/index.js:106:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
```

### Plugin version

5.2.1

**Comment by mkz212** [comment]
It has nothing to do with the plugin, only with Hoobs. This plugin is for Homebridge. It can work on Hoobs but it has never been tested.
