### ISSUE TITLE
Readable Stream is not defined

### ISSUE THREAD

**Issue by clw123456** [homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform#529]
### Description

Thanks for all the efforts in trying to resurrect this plugin, I updated this morning on HOOBS but still not working.

### Logs

```code
09/11/2024, 09:21:02Panasonic AC Bridge starting
09/11/2024, 09:21:06Panasonic AC BridgeErrorError loading plugin "homebridge-panasonic-ac-platform"
09/11/2024, 09:21:06Panasonic AC BridgeErrorReadableStream is not defined
09/11/2024, 09:21:06Panasonic AC BridgeErrorReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/var/lib/hoobs/panasonicacbridge/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/panasonicacbridge/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/hoobs/panasonicacbridge/node_modules/undici/index.js:106:19)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
09/11/2024, 09:21:06Panasonic AC BridgeWarningNo plugins installed.
09/11/2024, 09:21:06Panasonic AC BridgeLoading 1 platforms...
09/11/2024, 09:21:06Panasonic AC BridgeBridge is running on port 51856.
```

### Plugin version

5.3.0

**Comment by mkz212** [comment]
This is Hoobs error, not plugin. It is created for Homebridge and it is working on Homebridge. You must check Hoobs and report issue there.
